dropout_hidden: 0.3
dropout_post_conv: 0.6
edge_fea_len: 1
h_fea_len: 16
learning_rate: 0.009
save_path: weights/best_model.pt
n_conv: 1
n_h: 0
node_fea_len: 18
epochs: 150
output_size: 1
patience: 30
scheduler:
  factor: 0.5
  mode: min
  patience: 5
  threshold: 0.0001
  verbose: true
weight_decay: 0.0005
desired_feature_indices: [0,1,2,5,7,10,12,13,14, 15,16, 17, 18]
batch_size: 100
